import img from '../public/game.png';

const Events = [
    {
        id: "1",
        name: "Valorant (PC)",
        category: "Major Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "2",
        name: "BGMI (Mobile)",
        category: "Major Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "3",
        name: "CSGO (PC)",
        category: "Major Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "4",
        name: "Call of Duty (Mobile)",
        category: "Major Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "5",
        name: "Clash Royale",
        category: "General Games & Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "6",
        name: "Rocket League",
        category: "General Games & Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "7",
        name: "Free fire max ",
        category: "General Games & Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "8",
        name: "Fantasy Cricket Betting (26/3 27/3 )",
        category: "General Games & Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "9",
        name: " Webinar on 3D VR and AR",
        category: "General Games & Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "10",
        name: " Webinar promoting eSports in India by Team Velocity",
        category: "General Games & Events",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "11",
        name: "Game Quiz",
        category: "Events with Clubs",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "12",
        name: "Gamejam (GTA)",
        category: "Events with Clubs",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "13",
        name: "Housie (Rotaract)",
        category: "Events with Clubs",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "14",
        name: "Fan Art(Akriti)",
        category: "Events with Clubs",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "1",
        img: img.src,
        discord: "#"
    },
    {
        id: "15",
        name: "Chess + Workshop (Knights)",
        category: "Events with Clubs",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "16",
        name: "Debate (CSGO v/s Valorant) (Online game Addiction) (any other topic) (Clarion*)",
        category: "Events with Clubs",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "17",
        name: "4) Spot the Difference (online PPT)",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "18",
        name: "10) *Crossword/ Scrabble (Create our own related to NITR) ",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "19",
        name: "13) Send best/funniest game video to us and win goodies (we can ask people to vote in YouTube comments section)",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "20",
        name: "13) Guess the Sound - we will play certain game sounds and people will guess",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "21",
        name: "Call",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "22",
        name: "14) Pictionary",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "23",
        name: "15) Meme Competition- Games",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "24",
        name: "17) 21 Questions",
        category: "Fun Events (general and pre vridhi)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "25",
        name: "Among US",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "26",
        name: "Sudoku",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "27",
        name: "Type Racer (goodies)",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "28",
        name: "Valorant (with cheats on) sr\ replication",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "29",
        name: "Stumble Guys ( Fall guys)",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "30",
        name: "Skribble.io - Website",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "2",
        img: img.src,
        discord: "#"
    },
    {
        id: "31",
        name: " Ludo - Google Play Store",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "32",
        name: "Mini militia",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "33",
        name: "8 ball pool ",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    },
    {
        id: "34",
        name: "Uno",
        category: "Fun Events (games)",
        description: "lzfjghsdkjfhgkjdfh",
        teamSize: "4",
        prize: "6000",
        register: "#",
        date: "25",
        pdfLink: "#",
        registerLink: "#",
        day: "3",
        img: img.src,
        discord: "#"
    }
];

export default Events;